#ifndef BLINKER_AQI_CONFIG_H
#define BLINKER_AQI_CONFIG_H

#include <Arduino.h>

#define BLINKER_AQI_BASE_US 0
#define BLINKER_AQI_BASE_CN 1

#define BLINKER_LANGUAGE_CN 0
#define BLINKER_LANGUAGE_EN 1

#define BLINKER_PMS_RX_PIN D8
#define BLINKER_PMS_TX_PIN D9

#define BLINKER_WS2812_PIN D10

#define BLINKER_OLED_RESET_PIN U8X8_PIN_NONE

#endif